/*
 * useridentity
 * useridentity_descripton
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hasiltech.apiclient.useridentity;

import com.hasiltech.apiclient.ApiException;
import org.openapitools.client.model.LoginRequest;
import org.openapitools.client.model.LoginUserResponse;
import org.openapitools.client.model.RegisterRequest;
import org.openapitools.client.model.RegisterUserResponse;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthApi
 */
public class AuthApiTest {

    private final AuthApi api = new AuthApi();

    /**
     * Login user
     *
     * Login user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loginUserTest() throws ApiException {
        //
        //LoginRequest loginRequest = null;
        //
        //LoginUserResponse response = api.loginUser(loginRequest);

        // TODO: test validations
    }
    /**
     * Register user
     *
     * Register a new user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerUserTest() throws ApiException {
        //
        //RegisterRequest registerRequest = null;
        //
        //RegisterUserResponse response = api.registerUser(registerRequest);

        // TODO: test validations
    }
}
