/*
 * useridentity
 * User identity management service
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hasiltech.apiclient.useridentity;

import com.hasiltech.apiclient.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SystemControllerApi
 */
@Ignore
public class SystemControllerApiTest {

    private final SystemControllerApi api = new SystemControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void healthcheckTest() throws ApiException {
        String response = api.healthcheck();

        // TODO: test validations
    }
    
}
