/*
 * useridentity
 * Wave User Identity services 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hasiltech.apiclient.useridentity;

import com.hasiltech.apiclient.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.NewUserRequest;
import org.openapitools.client.model.NewUserResponse;
import org.openapitools.client.model.UserIdentityListResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserIdentityApi
 */
@Ignore
public class UserIdentityApiTest {

    private final UserIdentityApi api = new UserIdentityApi();

    
    /**
     * Create user identity
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUserIdentityTest() throws ApiException {
        NewUserRequest newUserRequest = null;
        NewUserResponse response = api.createUserIdentity(newUserRequest);

        // TODO: test validations
    }
    
    /**
     * List user identities
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUserIdentitiesTest() throws ApiException {
        UserIdentityListResponse response = api.listUserIdentities();

        // TODO: test validations
    }
    
}
